# Default values for sapcp-operator-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

manager:
  image:
    repository: ghcr.io/SAP/sap-btp-service-operator/controller
    tag: master
  secret:
    clientid:
    clientsecret:
    url:
    tokenurl:
cluster:
  id:
